services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: relay
    ports:
      - "5432:5432"
    volumes:
      - relay_db:/var/lib/postgresql/data

  api:
    image: node:20-alpine
    working_dir: /app/apps/api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/relay
    command: sh -lc "
      corepack enable &&
      pnpm config set ignore-scripts false &&
      pnpm install --frozen-lockfile &&
      pnpm rebuild @prisma/engines bcrypt esbuild prisma &&
      pnpm exec prisma migrate deploy --schema prisma/schema.prisma &&
      pnpm exec prisma generate --schema prisma/schema.prisma &&
      pnpm dev
      "
    ports:
        - "3000:3000"
        - "5555:5555"
    volumes:
      - .:/app
      - api_root_node_modules:/app/node_modules
      - api_app_node_modules:/app/apps/api/node_modules
    depends_on:
      - db

  web:
    image: node:20-alpine
    working_dir: /app/apps/web
    command: sh -lc "
      corepack enable &&
      pnpm config set ignore-scripts false &&
      pnpm install --frozen-lockfile &&
      pnpm rebuild esbuild &&
      pnpm dev --host 0.0.0.0
      "
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - web_root_node_modules:/app/node_modules
      - web_app_node_modules:/app/apps/web/node_modules
    depends_on:
      - api

volumes:
  relay_db:
  api_root_node_modules:
  api_app_node_modules:
  web_root_node_modules:
  web_app_node_modules:
